name: charts_flutter
version: 0.12.1
description: Material Design charting library for Flutter, updated for Dart 3.
homepage: https://github.com/Sardor6628/charts

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  charts_common: ^0.12.0
  collection: ^1.17.2
  intl: ^0.17.0
  logging: ^1.2.0
  meta: ^1.9.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  mockito: ^5.4.0
  test: ^1.25.8